version: 2
jobs:
  build:
    docker:
      - image: node:8.14
    steps:
      - checkout
      - restore_cache:
          key: dce-{{ checksum "./package.json" }}
      - run:
          name: Install NPM packages
          command: npm install
      - save_cache:
          key: dc-{{ checksum "./package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build ./dist
          command: npm run build
      - run:
          name: Deploy Staging
          command: |
            npm install -g firebase-tools@latest
            firebase deploy --token=$FIREBASE_TOKEN --non-interactive --project=$FIREBASE_PROJECT --only hosting

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
