name: SketchThat - Build & Deploy
run-name: ${{ github.actor }} Build & Deploy
on:
  push:
    branches: ["master"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install NPM
        run: npm install
      - name: Build ./dist
        run: npm run build
      - name: Install Firebase
        run: npm install -g firebase-tools@latest
      - name: Deploy hosting
        run: firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT }} --token ${{ secrets.FIREBASE_TOKEN }}
    